import { Inter, Poppins } from 'next/font/google'
import "./globals.css"
import 'funuicss/css/fun.css'
const mont_serrat = Poppins({
  subsets: ["latin"] ,
 weight: ['400', '700' , '100', '200' , '500' , '900' , '800'],
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mont_serrat.className}>{children}</body>
    </html>
  )
}
